name: Release Version
run-name: Release Version ${{ inputs.version }}
concurrency:
  group: release-new-version
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: NPM Version
        required: true
        type: string

env:
  NPM_VERSION: ${{ inputs.version }}

jobs:
  github-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm version --no-git-tag-version ${{ env.NPM_VERSION }}

      - name: Commit package.json
        uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: package*.json
          commit-message: "release: Bump version for ${{ env.NPM_VERSION }}"
          tag: v${{ env.NPM_VERSION }}